linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
  gocyclo:
    min-complexity: 15
  goconst:
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  revive:
    enable-all-rules: false
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf

linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - typecheck
    - gosimple
    - gofmt
    - goimports
    - misspell
    - unparam
    - unconvert
    - gocyclo
    - goconst
    - revive
    - gocritic

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
